### ISSUE TITLE
Update build system

### ISSUE THREAD

**Issue by matyasselmeci** [gridcf/UberFTP#2]
There are several tasks needed to finish the transfer of ownership of UberFTP to GCT:
- [x] Set up automated builds (Travis-CI) => see PR #16 
- [x] Add RPM packaging => see PR #15 
- [ ] Add Debian packaging?
- [x] Automate uploading sources to repo.gridcf.org => PR #17 
- [x] Update copyright? 
- [ ] Create GitHub releases

**Comment by fscheiner** [comment]
@matyasselmeci @msalle 
Just checked the network graph for UberFTP and noticed that we so far ignored the [develop branch](https://github.com/gridcf/UberFTP/commits/develop) from Jason Alt. We should maybe first include the changes from this branch (which itself include changes from the community) starting with https://github.com/gridcf/UberFTP/commit/6cd744627cbaadfc5797109060139b83cd1a2566 and then rebase #6 - if needed.

**Comment by msalle** [comment]
Good point, I had missed that. I suggest that - since we've already updated the master for the delete issue - that we bring the master in sync with devel: I've created PR #7 for that.
I've also created a new branch [autotools_cleanup_rebased](https://github.com/msalle/UberFTP/tree/autotools_cleanup_rebased) which is ready to be used for an updated PR once PR #7 is through.

**Comment by fscheiner** [comment]
@matyasselmeci @msalle
For RPM packaging:

I adapted the RPM spec file for UberFTP 2.8 from Fedora to our current code base and [the OBS successfully builds RPM packages for SUSE](https://build.opensuse.org/package/show/home:frank_scheiner:gct/uberftp) (based on ~2ea885b8338d9e99d458a674301318b9c9842ff4~ 13ce3730d4d06d8b4137a21957e5b3f35c80d4af ATM) now.

When we have a final UberFTP 2.9 I'll contact Steve Traylen to update the EPEL/Fedora packaging accordingly.

**Comment by fscheiner** [comment]
As we're already at it: The current RPM spec file includes [a conversion from ISO-8859 to UTF-8](https://src.fedoraproject.org/rpms/uberftp/blob/master/f/uberftp.spec#_32). This is due to NCSA's copyright statement as used in the UberFTP source code containing a copyright sign. This renders most files to ISO-8859. If you agree I'd change that to ASCII where possible, by changing the copyright sign to `(C)` or better `(c)` as ([the license as served from the OSI](https://opensource.org/licenses/NCSA) actually uses `(c)`). Or do you think "changing" the copyright statement creates a legal problem? :-)

**Comment by fscheiner** [comment]
~Find a matching commit for my above comment here:~

~https://github.com/fscheiner/UberFTP/commit/f519f204fb947738de62fab5e53c4cd8dbdcdf7f~

I created PR #14 for this. => merged as of now

**Comment by fscheiner** [comment]
@matyasselmeci, @msalle : 
I think I was too early when checking the box for "Update Copyright?" in https://github.com/gridcf/UberFTP/issues/2#issue-555694864 because the idea to replace the copyright symbols with ASCII text versions actually came later.

Was the original idea of that "task" to update the copyright for:
* https://github.com/gridcf/UberFTP/blob/master/COPYING

...and the files that have a copyright notice and that were modified by our commits?

But I think we don't do that for the GCT. And I also couldn't find any other copyright notices in the sources than from NCSA, although for example the IPv6 changes from @prelz were substantial.

**Comment by msalle** [comment]
Yes, that was the intention. I think it would be good to also include @ellert in this (being the expert).

**Comment by fscheiner** [comment]
> Yes, that was the intention. I think it would be good to also include @ellert in this (being the expert).

Indeed, @ellert, what's your opinion on https://github.com/gridcf/UberFTP/issues/2#issuecomment-829359013?
